// Port of internal/web/id.go. Same alphabet, same length, same rejection-
// sampling scheme, so page IDs generated by either backend have identical
// length/entropy/charset (12 base62 chars, ~71 bits, crypto-random).

const ID_ALPHABET =
  "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";
const ID_LEN = 12;

/** Returns a URL-safe, unguessable base62 identifier. Uses rejection sampling
 * (reject byte values >= 248) so every character is uniformly distributed
 * over the 62-symbol alphabet — no modulo bias, matching the Go implementation. */
export function newId(): string {
  const out: string[] = [];
  const buf = new Uint8Array(1);
  while (out.length < ID_LEN) {
    crypto.getRandomValues(buf);
    const value = buf[0]!;
    // 62*4 = 248; reject the top 8 values to keep the distribution uniform.
    if (value >= 248) continue;
    out.push(ID_ALPHABET[value % 62]!);
  }
  return out.join("");
}
